# Dockerfile for React
FROM node

# Set working directory inside the container
WORKDIR /app

# Copy only the package.json and install dependencies
COPY frontend/package.json ./

RUN npm install

# Copy the rest of the files
COPY ./frontend .

# Expose the port the app will run on
EXPOSE 3000

# Start the React app in development mode
CMD ["npm", "start"]
